#!/usr/bin/env python3
"""从页面 HTML 生成 / 校验 JSON-LD（task-19 第 3 步）。

为什么用脚本而不是手抄：
「FAQPage 与页面 FAQ 逐字对应」如果靠人抄，下一次改文案就会静默不一致
（结构化数据与页面说法不同，对 AI 与搜索结果都是一种说谎）。
这里**从 HTML 里抽文本**生成 JSON-LD，并在生成后立刻反向校验：
JSON-LD 里每一条 Q/A 必须能在页面可见文本里找到。

用法：
  python3 gen_jsonld.py gen      # 生成并写入两个页面的 <head>
  python3 gen_jsonld.py check    # 只校验（不改文件）
"""
import html
import json
import re
import sys
from pathlib import Path

# 脚本住在 <repo>/scripts/ 下，所以 site/ 在上一级。
# （早先它在仓库外的 .scratch/ 里，那时是 parents[1]/"xray-tun"/"site" ——
#  那样脚本不可持续：.scratch/ 是 gitignore 的，别人拿不到它。）
SITE = Path(__file__).resolve().parents[1] / "site"
PAGES = [
    {
        "path": SITE / "index.html",
        "lang": "zh-Hans",
        "url": "https://harodggg.github.io/xrayTun/",
        "name": "XrayTun",
        "description": "XrayTun 是面向 macOS 13 及以上的 Xray 图形客户端，使用 Xray-core 原生 TUN 入站接管系统流量。当前版本 v0.8.26，通用包（Apple Silicon + Intel），包内自带 Xray 核心。",
        "os": "macOS 13.0 or later",
    },
    {
        "path": SITE / "en" / "index.html",
        "lang": "en",
        "url": "https://harodggg.github.io/xrayTun/en/",
        "name": "XrayTun",
        "description": "XrayTun is an Xray GUI client for macOS 13 and later, using Xray-core's native TUN inbound to take over system traffic. Current version v0.8.26, universal build (Apple Silicon + Intel), Xray core included.",
        "os": "macOS 13.0 or later",
    },
]
DL = "https://github.com/harodggg/xrayTun/releases/download/v0.8.26/XrayTun_0.8.26_x86_64_arm64.dmg"
MARK_START = "<!-- JSON-LD: generated by .scratch/gen_jsonld.py — 改文案后重跑，别手改 -->"


def strip_tags(s: str) -> str:
    s = re.sub(r"<[^>]+>", "", s)
    s = html.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


def faq_pairs(src: str) -> list[tuple[str, str]]:
    """从 #faq 区块抽出 (问题, 答案)。答案取该 h3 之后、下一个 h3 之前的全部段落文本。"""
    start = src.index('id="faq"')
    block = src[start:]
    block = block[: block.index("</section>")]
    parts = re.split(r"<h3[^>]*>", block)[1:]
    out = []
    for p in parts:
        q_end = p.index("</h3>")
        q = strip_tags(p[:q_end])
        rest = p[q_end + 5 :]
        # 答案 = 后面的所有 <p> 文本拼接
        paras = re.findall(r"<p[^>]*>([\s\S]*?)</p>", rest)
        a = " ".join(strip_tags(x) for x in paras).strip()
        if q and a:
            out.append((q, a))
    return out


def build_ld(page: dict, faqs: list[tuple[str, str]]) -> list[dict]:
    return [
        {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": page["name"],
            "operatingSystem": page["os"],
            "applicationCategory": "UtilitiesApplication",
            "softwareVersion": "0.8.26",
            "softwareHelp": "https://harodggg.github.io/xrayTun/",
            "downloadUrl": DL,
            "installUrl": DL,
            "releaseNotes": "https://github.com/harodggg/xrayTun/blob/main/CHANGELOG.md",
            # 仓库已有 LICENSE（MIT）→ 指向它（2026-09-20 用户决定补上，commit 12c523d）
            "license": "https://github.com/harodggg/xrayTun/blob/main/LICENSE",
            "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
            "description": page["description"],
            "inLanguage": page["lang"],
        },
        {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "inLanguage": page["lang"],
            "mainEntity": [
                {
                    "@type": "Question",
                    "name": q,
                    "acceptedAnswer": {"@type": "Answer", "text": a},
                }
                for q, a in faqs
            ],
        },
    ]


def inject(path: Path, blocks: list[dict]) -> None:
    src = path.read_text(encoding="utf-8")
    payload = "\n".join(
        MARK_START
        + "\n"
        + '<script type="application/ld+json">'
        + json.dumps(b, ensure_ascii=False, indent=2)
        + "</script>"
        for b in blocks
    )
    # 幂等：先删掉上次生成的块
    src = re.sub(
        re.escape(MARK_START) + r'\s*<script type="application/ld\+json">[\s\S]*?</script>\s*',
        "",
        src,
    )
    assert "</head>" in src
    src = src.replace("</head>", payload + "\n  </head>", 1)
    path.write_text(src, encoding="utf-8")


def check() -> int:
    bad = 0
    for page in PAGES:
        src = page["path"].read_text(encoding="utf-8")
        blocks = re.findall(r'<script type="application/ld\+json">([\s\S]*?)</script>', src)
        if len(blocks) != 2:
            print(f"✗ {page['path'].name}: JSON-LD 块数 {len(blocks)}（期望 2）")
            bad += 1
            continue
        parsed = []
        for b in blocks:
            try:
                parsed.append(json.loads(b))
            except json.JSONDecodeError as e:
                print(f"✗ {page['path']}: JSON 解析失败 {e}")
                bad += 1
        app = next((p for p in parsed if p.get("@type") == "SoftwareApplication"), None)
        faq = next((p for p in parsed if p.get("@type") == "FAQPage"), None)
        if not app or not faq:
            print(f"✗ {page['path']}: 缺 SoftwareApplication 或 FAQPage")
            bad += 1
            continue
        # 页面可见文本（去标签）
        visible = strip_tags(src)
        page_faqs = faq_pairs(src)
        ld_faqs = [(q["name"], q["acceptedAnswer"]["text"]) for q in faq["mainEntity"]]
        ok = True
        if ld_faqs != page_faqs:
            print(f"✗ {page['path']}: FAQPage 与页面 FAQ 不一致（{len(ld_faqs)} vs {len(page_faqs)}）")
            ok = False
        for q, a in ld_faqs:
            if q not in visible:
                print(f"✗ {page['path']}: 问题不在页面里：{q[:40]}")
                ok = False
            if a[:60] not in visible:
                print(f"✗ {page['path']}: 答案前 60 字不在页面里：{a[:60]}")
                ok = False
        if app["operatingSystem"] != "macOS 13.0 or later":
            print(f"✗ {page['path']}: operatingSystem 不是「仅 macOS」")
            ok = False
        # 许可证事实（2026-09-20 起）：源码 MIT 且仓库有 LICENSE；随包 Xray-core 是 MPL-2.0。
        # 这里锁住「不能既不说 MIT 也不给出 LICENSE 链接」以及「必须提 MPL-2.0」，
        # 而不是像以前那样禁止出现 MIT（那已经过期）。
        lic = str(app.get("license", ""))
        faq_text = json.dumps(faq, ensure_ascii=False)
        if not lic.endswith("/LICENSE") or "MPL-2.0" not in faq_text:
            print(f"✗ {page['path']}: license 字段应指向 /LICENSE，且 FAQ 必须写明随包 Xray-core 是 MPL-2.0")
            ok = False
        print(
            f"{'✓' if ok else '✗'} {page['path'].relative_to(SITE)}: JSON.parse ok · "
            f"SoftwareApplication ok · FAQPage {len(ld_faqs)} 条与页面逐条一致 · 可见文本 {len(visible)} 字"
        )
        bad += 0 if ok else 1
    return bad


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "check"
    if mode == "gen":
        for page in PAGES:
            faqs = faq_pairs(page["path"].read_text(encoding="utf-8"))
            inject(page["path"], build_ld(page, faqs))
            print(f"  写入 JSON-LD：{page['path'].relative_to(SITE)}（FAQ {len(faqs)} 条）")
        mode = "check"
    if mode == "check":
        bad = check()
        print("结论:", "全部通过" if bad == 0 else f"{bad} 处不一致")
        return 1 if bad else 0
    return 2


if __name__ == "__main__":
    sys.exit(main())
